# Generated by Django 2.0 on 2017-12-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=39)),
                ('external_ip', models.CharField(max_length=39)),
                ('timestamp', models.DateTimeField(verbose_name='transmission started')),
                ('ping', models.CharField(max_length=10)),
                ('ping_destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=200)),
                ('location_of_pi', models.CharField(max_length=17)),
            ],
        ),
        migrations.AddField(
            model_name='networkdata',
            name='node_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkconnectivity.NetworkNode'),
        ),
    ]
