# Generated by Django 2.0 on 2017-12-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkconnectivity', '0002_auto_20171209_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdata',
            name='node_name',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='networkdatas', to='networkconnectivity.NetworkNode', verbose_name='networknode'),
        ),
    ]
