# Generated by Django 2.0 on 2017-12-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkconnectivity', '0003_auto_20171209_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdata',
            old_name='node_name',
            new_name='node',
        ),
    ]
